In [3]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Arrays and Operations

In [4]:
# To make an an array use make_array()


array([1, 2, 3, 4], dtype=int64)

In [7]:
# entries in an array must be of the same data type
#otherwise errors or unkwown effects occur



array(['1', '2', '43', 'False'], dtype='<U11')

In [8]:
#lets add two arrays together



array([ 2,  4,  6,  8, 10, 12], dtype=int64)

In [9]:
# lets try multiplication
# remember operations are applied elementwise


array([ 1,  4,  9, 16, 25, 36], dtype=int64)

In [14]:
# 
# Operations between an array and a real number is down element wise 
# For example if we multiply a number times a1


array([ 2,  4,  6,  8, 10, 12], dtype=int64)

In [15]:
#
#If we expontentation 2 by a1
#each 2 is raised by each element



array([ 2,  4,  8, 16, 32, 64], dtype=int64)

In [17]:
#
#Order of operation does matter for exponentation
#if we switch the order then we are raising each element by a power of 2 



array([ 1,  4,  9, 16, 25, 36], dtype=int64)

## Array Functions and Methods

In [21]:
# Lets go ahead and make an array of random heights in inches


array([67, 60, 71, 63, 65], dtype=int64)

In [22]:
# If we divide heights by 12 we get the heights in inches 


array([5.58333333, 5.        , 5.91666667, 5.25      , 5.41666667])

In [23]:
# We can find the length of an array using len (for length)


5

In [26]:
# lets compute the average value by the formula first
# sum / number of entries


65.2

65.2

In [31]:
#


65.2

In [ ]:
# Lets make an array of strings 
# and try out the .item


In [ ]:
# again positions in arrays start at zero
# so the last element should be in position


In [ ]:
# What about the second element


## Ranges ##

In [ ]:
# we can make an array by hand


In [ ]:
# if we want an extremely long array 
# lets make an array go from 0 ,5


# remeber if we only have one number we are saying make an array from 0 -6 not including 6

In [ ]:
# We can start the value were ever we want 
# lets make an array from 5,10


In [ ]:
# We can also determine how many numbers to increase by! 


## Creating a Table from Scratch ##

In [32]:
#Lets go ahead and make our own table
# First we will make an array of strings


array(['bannana', 'apple', 'orange'], dtype='<U7')

In [34]:
#To make a table we must make an empty table and add a column
# here is an empty table


In [35]:
#lets add our fruit column to an empty table and call the column fruit
# the first entry is the new solumn name the second entry is the array


fruit
bannana
apple
orange

In [37]:
#All columns in a table must be the same length
#lets add another column with the cost of each fruit


#bannans are free

fruit   | cost
bannana | 0
apple   | 1
orange  | 2

In [38]:
#lets check our new table 


fruit
bannana
apple
orange

In [39]:
# make sure to save the table! 

fruit   | cost
bannana | 0
apple   | 1
orange  | 2

## Reading a Table from a File  ##

In [57]:
# here we have his data 
# the first couloumn is the average income per year of an Black family in the early 1900
# the other columns are how much they spend on other expenses
# the rows represeent the different classes 



CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [59]:
# Which group ("CLASS") spent the highest percentage on rent?
# try to find the hights rent



CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [61]:
# lets find the average that each class spends on food !


FOOD
0.43
0.47
0.43
0.37
0.31
0.37
0.29

In [63]:
# This is a preview for the next lecture but we can use column to get the column array
foodcost=du_bois.select('FOOD').column('FOOD')


0.3814285714285714

## Selecting data in a column ##

In [ ]:
movies = Table.read_table('movies_by_year_with_ticket_price.csv')
movies.show()

In [ ]:
gross_in_dollars = movies.column('Total Gross') * 1e6
tix_sold = gross_in_dollars / movies.column('Average Ticket Price')

In [ ]:
movies = movies.with_column('Tickets sold', tix_sold)

In [ ]:
movies.show(4)

In [ ]:
movies.set_format('Tickets sold', NumberFormatter)

In [ ]:
movies.plot('Year', 'Tickets sold')

In [ ]:
movies.where('Year', are.between(2000, 2005))

In [ ]:
movies.where('Year', 2002)

In [ ]:
movies.where('Year', are.equal_to(2002))

In [ ]:
movies.where('#1 Movie', are.containing('Harry Potter'))

In [ ]:
movies.take(np.arange(2, 5))